name: Reusable Deploy
on: workflow_call #this event allows this workflow to be called by other workflows
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Output Information
              run: echo "Deploying and uploading..."