name: Reusable Deploy
on: 
    workflow_call:
        inputs: #https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context
            artifact-name:
                description: The name of the deployable artifact files
                required: false
                default: dist
                type: string 
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/download-artifact@v3
              with: 
                name: ${{inputs.artifact-name}}
            - name: List files
              run: ls
            - name: Output Information
              run: echo "Deploying and Uploading"
